import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  <nav style={{ padding: "20px", borderBottom: "1px solid #ddd" }}>
    <a href="/" style={{ marginRight: "16px" }}>Home</a>
    <a href="/teams">Teams</a>
  </nav>

  <div style={{ padding: "20px" }}>
    {children}
  </div>
</body>

    </html>
  );
}
